[project]
name = "bundle-delegate"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.delegation-governance]
path = "contracts/delegation-governance.clar"
depends_on = []

[contracts.bundle-market]
path = "contracts/bundle-market.clar"
depends_on = []

[contracts.delegation-rep]
path = "contracts/delegation-rep.clar"
depends_on = []

[contracts.bundle-license]
path = "contracts/bundle-license.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
